apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codgen-onesixtest-may29
  janus-idp.io/tekton: codgen-onesixtest-may29
  backstage.io/kubernetes-id: codgen-onesixtest-may29
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codgen-onesixtest-may29
resources:
  - application-dev.yaml