apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: codgen-onesixtest-may29
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codgen-onesixtest-may29
  name: codgen-onesixtest-may29
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
